services:
  db:
    image: postgres
    container_name: some-postgres
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
