// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package product

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) (DecreaseProductStockRow, error)
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	GetProductById(ctx context.Context, id uuid.UUID) (GetProductByIdRow, error)
	GetProducts(ctx context.Context) ([]GetProductsRow, error)
	GetProductsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]GetProductsByIdsRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
