// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package order

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
}

var _ Querier = (*Queries)(nil)
