// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusCompleted OrderStatus = "completed"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Order struct {
	ID        uuid.UUID
	Userid    uuid.UUID
	Total     string
	Status    OrderStatus
	Address   string
	Createdat time.Time
	Updatedat time.Time
	Deletedat sql.NullTime
}

type OrderItem struct {
	ID        uuid.UUID
	Orderid   uuid.UUID
	Productid uuid.UUID
	Quantity  int32
	Price     string
}

type Product struct {
	ID          uuid.UUID
	Name        string
	Description string
	Image       string
	Price       string
	Quantity    int32
	Createdat   time.Time
	Updatedat   time.Time
	Deletedat   sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Firstname string
	Lastname  string
	Email     string
	Password  string
	Createdat time.Time
	Updatedat time.Time
	Deletedat sql.NullTime
}
